title: Bruno Mendes
email: bd_mendes@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Bruno Mendes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bdmendes
author: Bruno Mendes
icon: bdmendes.ico

social:
  - name: github
    icon: github-line.svg
    url: https://github.com/bdmendes
  - name: linkedin
    icon: linkedin-fill.svg
    url: https://www.linkedin.com/in/bdmendes/
  - name: email
    icon: mail-line.svg
    url: mailto:bd_mendes@outlook.com

navigation:
  - name: About
    url: /
  - name: Blog
    url: /blog
  - name: Poetry
    url: /poetry
  - name: Misc
    url: /misc

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Blog settings
paginate: 4
paginate_path: "blog/page:num"

# Aditional collections
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:title
  poetry:
    output: true
  slides:
    output: true
  projects:
    output: false
