title: Bruno Mendes
email: bd_mendes@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Bruno Mendes is a student passionate about low level development and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bdmendes
profile_picture: assets/about-me/bdmendes.jpg
author: Bruno Mendes

social:
  - name: github/bdmendes
    icon: ri-github-line
    url: https://github.com/bdmendes
  - name: linkedin/bdmendes
    icon: ri-linkedin-fill
    url: https://www.linkedin.com/in/bdmendes/
  - name: email
    icon: ri-mail-line
    url: mailto:bd_mendes@outlook.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Aditional collections
collections:
  music:
  movies:
  series:
  paradoxo:
    output: true
