title: Bruno Mendes
email: bd_mendes@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Bruno Mendes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bdmendes
profile_picture: assets/about-me/bdmendes.jpg
author: Bruno Mendes
icon: bdmendes.ico

social:
  - name: github/bdmendes
    icon: github-line.svg
    url: https://github.com/bdmendes
  - name: linkedin/bdmendes
    icon: linkedin-fill.svg
    url: https://www.linkedin.com/in/bdmendes/
  - name: email
    icon: mail-line.svg
    url: mailto:bd_mendes@outlook.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Blog settings
paginate: 4
paginate_path: "blog/page:num"

# Aditional collections
collections_dir: collections
collections:
  projects:
  paradoxo:
    output: true
